name: Scala Steward

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'images/**'
      - README.md
  
  schedule:
    # Schedule to run every Sunday @ 12PM UTC. Replace this with
    # whatever seems appropriate to you.
    - cron: "0 0 * * 0"
  # Provide support for manually triggering the workflow via GitHub.
  workflow_dispatch:

jobs:
  scala-steward:
    name: scala-steward
    runs-on: ubuntu-latest
    steps:
      # This is necessary to ensure that the most up-to-date version of
      # REPOSITORIES.md is used.
      - uses: actions/checkout@v2

      # Cache SBT dependencies to speed up the build process
      #- name: Cache SBT dependencies
       # uses: actions/cache@v2
        #with:
         # path: ~/.ivy2/cache
          #key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          #restore-keys: |
           #   ${{ runner.os }}-sbt-

      # Run Scala Steward
      - name: Fetch shared Scala Steward config
        run: |
          curl -o .scala-steward.conf https://github.com/open-electrons/open-electrons-templates/blob/master/common-templates/scala-steward.conf
      - name: Execute Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.72.0
        with:
          # A GitHub personal access token tied to a user that will create
          # pull requests against your projects to update dependencies. More
          # on this under the YAML snippet.
          github-token: ${{ secrets.SCALA_STEWARD_GITHUB_TOKEN }}
          # A Markdown file with a literal Markdown list of repositories
          # Scala Steward should monitor.
          repos-file: repos.md
          author-email: scala-steward@users.noreply.github.com
          author-name: Scala Steward
